Cluster management backend
lumjjb/tornjak pull request #67
Opened 2021-06-21 19:14 UTC by maia-iyer

2021-06-22 17:24 UTC, lumjjb reviewed
Looks good so far - as we chatted about, making some changes to the database schema and making `ClusterInfo` struct a bit more usable (not needing to stay close to the db schema).

2021-06-28 15:58 UTC, lumjjb requested changes
Awesome work so far! Looking good, couple comments around DB and interfaces, good testing!

2021-06-28 15:58 UTC, lumjjb commented on tornjak-backend/api/agent/server.go
> +  if err != nil {
can you run `go fmt ./...` to format the files

2021-06-28 15:58 UTC, lumjjb commented on tornjak-backend/api/agent/server.go
> +	buf := new(strings.Builder)
nit: for consistency let's add the endpoint hit print 

i.e.
```
	fmt.Println("Endpoint Hit: Cluster List")
```

2021-06-28 15:58 UTC, lumjjb commented on tornjak-backend/api/agent/server.go
> +	buf := new(strings.Builder)
nit: for consistency let's add the endpoint hit print 

i.e.
```
	fmt.Println("Endpoint Hit: Cluster List")
```

2021-06-28 15:58 UTC, lumjjb commented on tornjak-backend/api/agent/server.go
> +	rtr.HandleFunc("/api/tornjak/cluster/create", corsHandler(s.clusterCreate))
let's make this consistent and make them all `clusters/...`

2021-06-28 15:58 UTC, lumjjb commented on tornjak-backend/api/manager/server.go
> +	rtr.HandleFunc("/manager-api/tornjak/cluster/create/{server:.*}", corsHandler(s.apiServerProxyFunc("/api/tornjak/cluster/create")))
let's make this consistent and make them all clusters/...

2021-06-28 15:58 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/db.go
> +	RemoveClusterAgents(clusterName string) error
Be careful of the atomic implications of these interface calls

2021-06-28 15:58 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite.go
> +	cmdCheckExistence := "SELECT name FROM clusters WHERE name=?"
May want to take a look at counting 1 so that the database can stop when it find something

Can look at a combination of `rownum = 1` or `EXISTS`
https://stackoverflow.com/questions/14566910/identify-if-at-least-one-row-with-given-condition-exists

2021-06-28 15:58 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite.go
> +	_, err := db.GetAgentClusterName(spiffeid)
I think this isnt required if you set the table fields to be a FOREIGN key to link the two tables... so this can be done with the updates where you can do something like the following with the help of WHERE statements / subroutines

`INSERT OR REPLACE .... VALUES (?,?) WHERE ....`

2021-06-28 15:58 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/db.go
> +	AssignAgentCluster(spiffeid string, clusterName string) error
Probably better by assigning multiple agents... DB calls are generally expensive

2021-06-28 15:58 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/db.go
> +	RemoveClusterAgents(clusterName string) error
I would remove these agent interfaces for now and just roll it into `ClusterInfoEdit` for now... The implications of how these are used are messy because of the cost of Database calls and ensuring ACID properties of the types of operations we want to do.

2021-06-28 15:58 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite.go
> +	cmdFindCluster := "SELECT name FROM clusters WHERE name=?"
I don't think this is necessary if we set the name column to be the db UNIQUE property. Doing the update will throw the error

2021-06-28 15:58 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite.go
> +	var name string
We talked about this during the call, the entire operation needs to be atomic, check out SQL transactions to do this

2021-06-28 15:58 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite.go
> +	cmdFindCluster := "SELECT name FROM clusters WHERE name=?"
don't think we need this, the returned output/errors from the delete DB query should give us all the information needed to determine if the cluster didn't exist...

Also, if you think about this a bit more, getting an OK query return from this select doesn't necessary mean that it won't exist when the next delete call is made.... Think race condition between 2 people that want to delete the cluster...

2021-06-28 15:58 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite_errors.go
> +
nice error management

2021-06-28 15:58 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite_test.go
> +	if len(agents) != 2 || agents[0] != agent1 || agents[1] != agent2 {
not sure if there can be any assertion of the ordering of the results.... may want to do a "set" comparison instead of a "list" comparison

2021-06-28 15:58 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite_test.go
> +
Great tests!!!

nit: can you add a comment for the tests to describe what they do in the godoc style, thanks!

```
// TestClusterCreate checks ...
func TestClusterCreate(t *testing.T) {
```

2021-06-28 15:58 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite_test.go
> +func TestClusterCreate(t *testing.T) {
This function is a bit long, would be helpful to add some comment blocks to describe what is being done in each section since the comparison checks in tests can get quite cryptic

2021-06-28 15:58 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite_test.go
> +	if len(agents) != 2 || agents[0] != agent1 || agents[1] != agent2 {
note on ordering above

2021-06-28 15:58 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite_test.go
> +	if len(cList) != 1 || storedCinfo.Name != cinfo1New.Name || storedCinfo.ManagedBy != cinfo1New.ManagedBy || storedCinfo.PlatformType != cinfo1New.PlatformType {
for agent checking and cluster info comparison, it would probably be helpful to write 1 or 2 helper functions instead to make things more readable.

2021-06-29 13:34 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite.go
> +	database, err := sql.Open("sqlite3", dbpath) // TODO close DB upon error?
if it is an error, it implies that the database was not successfully created, so the database object is not instantiated or valid.

2021-06-29 13:34 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite.go
> +		return nil, err
probably can put this in a loop

2021-06-29 13:34 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite.go
> +		return errors.New("Could not get context")
it should return the error, there is no guarantee that it failed because of context.

2021-06-29 13:34 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite.go
> +func (db *LocalSqliteDb) checkClusterExistence(ctx context.Context, tx *sql.Tx, name string) (bool, error) {
probably this would be better by creating a new local struct called a 
```
type tornjakDbTransaction struct {
    ctx context.Context
    tx *sql.Tx
}

```

And then these can be 
```
func (t *tornjakDbTransaction) checkClusterExistence (name string) (bool, error)
....
```

and then at the end you can just get the transaction from the struct.

Since we don't really need the original DB object in building the transaction and we dont need to keep passing these things around. 


HOWEVER, if you decide to do this, then it is generally not good practice to manually add things to the internal transaction via direct calls to `QueryContext`, it would need a helper function, and all these helper functions can be moved to a different file

2021-06-29 13:34 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite.go
> +	cmd := "SELECT clusters.name, clusters.domainName, clusters.managedBy, clusters.platformType, GROUP_CONCAT(clusterMemberships.spiffeid) FROM clusters LEFT JOIN clusterMemberships ON clusters.id=clus
can we make this a multiline string instead for better readability?

2021-06-29 13:34 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite.go
> +func (db *LocalSqliteDb) GetAgentClusterName(spiffeid string) (string, error) {
This can be done in 1 SQL statement, check out querying over multiple tables (i.e. implicit joins)

2021-06-29 13:39 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite.go
> +	rows, err := tx.QueryContext(ctx, cmdFindCluster, name)
it seems like transactions may not be used in the best way since each part of the transaction is queried, thus holding the lock while other logic is being done outside the database, it would be better to prepare the entire transaction and let the Database handle the entirety of it

2021-06-29 14:24 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite.go
> +func (db *LocalSqliteDb) GetAgentClusterName(spiffeid string) (string, error) {
Something like

`SELECT A.field1 FROM tablea as A, tableb as B WHERE A.id = B.fkid AND B.name = ?`

2021-06-29 14:24 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite.go
> +func (db *LocalSqliteDb) GetAgentClusterName(spiffeid string) (string, error) {
https://stackoverflow.com/questions/1416003/sql-select-from-multiple-tables

2021-06-29 14:34 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite.go
> +	} else if clusterExists {
put this as a new line without else

2021-07-07 16:15 UTC, lumjjb reviewed
Awesome - couple nits, and 1 or 2 requested changes, and should be good to merge soon!

2021-07-07 16:15 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite.go
> +	cmd := `SELECT clusters.name, clusters.domainName, clusters.managedBy,
Should this use a `txHelper` function abstraction instead?

2021-07-07 16:15 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite.go
> +	return tx.Commit()
question: if commit fails, is `rollbackHandler` required to be called? 

I think that we may want to handle transaction failures with a retry with a small random backoff, up to a certain amount (configurable), and if it still fails then return the error... Since a transaction can fail just due to contention on a resource.

2021-07-07 16:15 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite_test.go
> +	} else if len(correctList) > len(resultList) {
how about `len(resultList) != len(correctList)`, usually when an error is returned, the message is usually list are not the same, expected %v, got %v, so we don't have to return additional information about the comparison as the err msg

2021-07-07 16:15 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite_test.go
> +	if c1.Name != c2.Name || c1.DomainName != c2.DomainName || c1.ManagedBy != c2.ManagedBy || c1.PlatformType != c2.PlatformType {
nit: put these in multiple lines, should be able to create a new line after a `||`

2021-07-07 16:15 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite_test.go
> +func inList(elem string, list []string) bool {
nit: have a comment on for `/**** HELPER SECTION ****/`, also would like to put this at the end of file instead of start of the file

2021-07-07 16:15 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite_txhelpers.go
> +			return errors.Errorf("%v%v", err.Error(), rollbackStatus)
nit: `%v:%v`

2021-07-07 16:15 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite_txhelpers.go
> +		if serr, ok := err.(sqlite3.Error); ok {
nit; 

`if serr, ok := err.(sqlite3.Error); ok && serr.Code == sqlite3.ErrConstraint {`

2021-07-07 16:15 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite_txhelpers.go
> +			cmdBatch = cmdBatch + fmt.Sprintf(",(\"%v\", (SELECT id FROM clusters WHERE name=\"%v\"))", agentsList[i], clustername)
This pattern is dangerous, you should not be substituting variables in SQL statements via `Sprintf`, this will create SQL injection vulnerabilities since a user is now able to change the SQL statement. Can you see if there's a way to do this with the sqlite library instead?

2021-07-07 21:21 UTC, maia-iyer commented on tornjak-backend/pkg/agent/db/sqlite.go
> +	return tx.Commit()
If a commit fails, I do not believe we need to rollback; sql transactions should be able to handle it

2021-07-08 17:54 UTC, lumjjb approved these changes
LGTM - 1 minor nit. Thanks @maia-iyer

2021-07-08 17:54 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite_txhelpers.go
> +	cmdBatch = cmdBatch[0 : len(cmdBatch)-1]
better to do `strings.TrimSuffix(",")` instead, a little less cryptic

2021-07-08 17:54 UTC, lumjjb commented on tornjak-backend/pkg/agent/db/sqlite_txhelpers.go
> +	}
This is a good fix! Nice.

2021-07-08 20:20 UTC, merged