Updated dashboard pie-chart labels
lumjjb/tornjak pull request #94
Opened 2021-08-04 15:31 UTC by mrsabath

Signed-off-by: Mariusz Sabath <sabath@us.ibm.com>

2021-08-04 19:53 UTC, mamy-CS requested changes
Other than removing package.json from .gitignore lgtm!

2021-08-04 19:53 UTC, mamy-CS commented on .gitignore
> +package.json
package.json should not be added to .gitignore.

2021-08-05 14:47 UTC, mrsabath commented on .gitignore
> +package.json
I think there are at least 2 `package.json` files. One is in the root of tornjak, and this one should be ignored, since we don't have it in the tree, the second one is in `tornjak-frontend/package.json` and I agree, that one we should keep. 
Please confirm my understanding.

2021-08-05 14:55 UTC, mamy-CS commented on .gitignore
> +package.json
Yes, there should not be a /package.json in the root (I don't have one in mine). Only tornjak-frontend/package.json. In that case all good.

2021-08-05 14:56 UTC, mamy-CS approved these changes

2021-08-05 16:48 UTC, lumjjb commented on .gitignore
> +package.json
I think this will also flag the inside `package.json` as well, @mrsabath can you test this?

2021-08-05 17:08 UTC, mrsabath commented on .gitignore
> +package.json
I tested it earlier. It ignores only the one in root directory. We are good here.

2021-08-05 17:19 UTC, merged